"""Framework-neutral contracts for generated visual panels."""

from .contracts import (
    ActivePanelState,
    ActiveSurfaceSummary,
    AnchorBinding,
    ChoiceChild,
    ComponentChild,
    ComponentNode,
    CreateSurfacePlan,
    UseExistingSurfaceTemplate,
    DeleteSurface,
    AddBlockOperation,
    RemoveBlockOperation,
    ReplaceBlockOperation,
    MoveBlockOperation,
    UpdatePropsOperation,
    ReplaceChildrenOperation,
    PatchSurfacePlan,
    PlanBlock,
    DataAlias,
    DataBundle,
    GridRect,
    PresentationPlan,
    RouteRequest,
    SurfaceDocument,
    surface_plan_command_from_dict,
)
from .compiler import CANVAS_COLUMNS, CANVAS_ROWS, PanelCompilationError, PanelCompiler
from .renderers import render_visual_stage_map, surface_document_client_payload

__all__ = [
    "ActivePanelState",
    "ActiveSurfaceSummary",
    "AnchorBinding",
    "ChoiceChild",
    "ComponentChild",
    "ComponentNode",
    "CreateSurfacePlan",
    "UseExistingSurfaceTemplate",
    "DeleteSurface",
    "AddBlockOperation",
    "RemoveBlockOperation",
    "ReplaceBlockOperation",
    "MoveBlockOperation",
    "UpdatePropsOperation",
    "ReplaceChildrenOperation",
    "PatchSurfacePlan",
    "PlanBlock",
    "DataAlias",
    "DataBundle",
    "GridRect",
    "PresentationPlan",
    "RouteRequest",
    "SurfaceDocument",
    "surface_plan_command_from_dict",
    "CANVAS_COLUMNS",
    "CANVAS_ROWS",
    "PanelCompilationError",
    "PanelCompiler",
    "surface_document_client_payload",
    "render_visual_stage_map",
]
