"""Framework-neutral contracts for generated visual panels."""

from .contracts import (
    ActivePanelState,
    ActiveSurfaceSummary,
    AnchorBinding,
    BlockState,
    ChoiceChild,
    CreateSurfacePlan,
    UseExistingSurfaceTemplate,
    DeleteSurface,
    AddBlockOperation,
    RemoveBlockOperation,
    ReplaceBlockOperation,
    MoveBlockOperation,
    UpdatePropsOperation,
    PatchSurfacePlan,
    PanelBlock,
    PanelChoiceChild,
    PlanBlock,
    DataAlias,
    DataBundle,
    GridRect,
    PanelIR,
    PresentationPlan,
    RouteRequest,
    SurfaceBlock,
    SurfaceState,
    SurfaceStructure,
    materialize_panel_ir,
    surface_plan_command_from_dict,
)
from .compiler import CANVAS_COLUMNS, CANVAS_ROWS, PanelCompilationError, PanelCompiler
from .renderers import panel_client_payload, render_visual_stage_map

__all__ = [
    "ActivePanelState",
    "ActiveSurfaceSummary",
    "AnchorBinding",
    "BlockState",
    "ChoiceChild",
    "CreateSurfacePlan",
    "UseExistingSurfaceTemplate",
    "DeleteSurface",
    "AddBlockOperation",
    "RemoveBlockOperation",
    "ReplaceBlockOperation",
    "MoveBlockOperation",
    "UpdatePropsOperation",
    "PatchSurfacePlan",
    "PanelBlock",
    "PanelChoiceChild",
    "PlanBlock",
    "DataAlias",
    "DataBundle",
    "GridRect",
    "PanelIR",
    "PresentationPlan",
    "RouteRequest",
    "SurfaceBlock",
    "SurfaceState",
    "SurfaceStructure",
    "materialize_panel_ir",
    "surface_plan_command_from_dict",
    "CANVAS_COLUMNS",
    "CANVAS_ROWS",
    "PanelCompilationError",
    "PanelCompiler",
    "panel_client_payload",
    "render_visual_stage_map",
]
